#!/usr/bin/env bash
# install nginx web server on web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html 
sudo service nginx restart
